config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'

  resources :recipes, only: %i[index show new create update edit] do
    collection do
      get 'search'
    end
    get 'my_recipes', on: :member
  end
  
  resources :recipe_types, only: %i[show new create]
  resources :recipe_lists, only: %i[show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  belongs_to :user

  validates :tittle, :user, :recipe_type_id, :cuisine, :difficulty, :cook_time, :ingredients, :cook_method, presence: { message: 'Campo obrigatório!'}
  
  def cook_time_min
    return "#{self.cook_time} minutos"
  end

  def form_date(date)
    # formatting date: Aug, 31 2007 - 9:55PM
    date.strftime("%d/%m/%Y às %H:%M")
  end

  def owner?(user)
    self.user == user
  end
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: { message: 'Campo obrigatório!' }
  validates :name, uniqueness: { message: 'Campo duplicado!' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  def recipe_owner?(recipe)
    if self == recipe.user
      return true
    else
      return nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  def new
    @recipe_list = RecipeList.new
  end

  def create
    @recipe_list = RecipeList.create(params.require(:recipe_list).permit(:name))
    redirect_to @recipe_list
    flash[:notice] = 'Lista criada com sucesso!'
  end

  def show 
    @recipe_list = RecipeList.find(params[:id])
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
      flash[:notice] = 'Novo tipo de receita cadastrado com sucesso!'
      redirect_to @recipe_type
    else
      flash.now[:alert] = 'Tipo de receita não cadastrado!'
      render :new
    end
  end

  def show
    @recipe_type = RecipeType.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_params_id, only: %i[show edit update]
  before_action :load_recipe_type, only: %i[new create edit update]
  before_action :authenticate_user!, only: %i[new create edit update]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipes = Recipe.new
  end

  def show; end

  def create
    @recipes = Recipe.create(set_params)
    @recipes.user = current_user
    
    if @recipes.save
      flash[:notice] = 'Receita criada com sucesso!'
      redirect_to @recipes
    else
      flash.now[:alert] = 'Receita não cadastrada.'
      render :new
    end
  end

  def edit
    redirect_to root_path if !@recipes.owner? current_user
  end

  def update
    if @recipes.update(set_params)
      redirect_to @recipes
    else
      flash.now[:alert] = 'Não foi possível salvar a receita'
      render :edit
    end
  end

  def search
    @recipes = Recipe.where('tittle LIKE ?', "%#{params[:name]}%")
    if @recipes.empty?
      flash.now[:alert] = 'Nenhuma receita encontrada.'      
    end
  end

  def my_recipes
    @recipes = Recipe.where("user_id = #{params[:id]}")
  end

  private

  def set_params
  	params.require(:recipe).permit(:tittle, :recipe_type_id, :cuisine,
  								   :difficulty, :cook_time, :ingredients, :cook_method, :user)
  end

  def set_params_id
    @recipes = Recipe.find(params[:id])
  end

  def load_recipe_type
    @recipe_types = RecipeType.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook - TreinaDev - João Barbieri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="titulo">CookBook</h1>
    <p align="center">Bem-vindo ao maior livro de receitas online!</p>
    <br>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-buttons' %>
        <%= link_to 'Nova Receita', new_recipe_path, class: 'nav-buttons' %>
        <%= link_to 'Novo Tipo de Receita', new_recipe_type_path, class: 'nav-buttons' %>      
        <%= link_to 'Nova Lista', new_recipe_list_path, class: 'nav-buttons' %>      
        <%= link_to 'Minhas Receitas', my_recipes_recipe_path(current_user), class: 'nav-buttons' %>      
      <% else %>
        <%= link_to 'Entrar', new_user_session_path, class: 'nav-buttons' %>
      <% end %>

    </nav>

    <hr>
      <%= form_tag search_recipes_path, method: 'get', class: 'buscar' do %>
        <%= label_tag(:name, "Buscar receitas:") %>
        <%= text_field_tag(:name) %>
        <%= submit_tag("Buscar") %>
      <% end %>
    <hr>
    
    <span style="text-align: center;"><%= flash[:alert] %></span>
    <span style="text-align: center;"><%= flash[:notice] %></span>

    <% if user_signed_in? %>
      <span style="text-align: center;"><p>Olá, <%= current_user.email %>!</p></span>
    <% end %>
    <br>

    <%= yield %>
  </body>
</html>

app/views/recipe_lists/new.html.erb
<% @recipe_list.errors.full_messages.each do |msg| %>
  <%= msg %>
<% end %>

<%= form_for @recipe_list do |f| %>
  <%= f.label :name, 'Nome da lista' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipe_lists/show.html.erb
  <h1><%= @recipe_list.name %></h1>
  <%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipe_types/_form_types.html.erb
<% @recipe_type.errors.full_messages.each do |msg| %>
  <%= msg %>
<% end %>

<%= form_for @recipe_type do |f| %>
  <%= f.label :name, 'Novo Tipo de Receita' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipe_types/new.html.erb
<h1>Novo Tipo de Receita</h1>

<%= render partial: 'form_types' %>

app/views/recipe_types/show.html.erb
  <h1><%= @recipe_type.name %></h1>
  <%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipes/_form_recipes.html.erb
<% if @recipes.errors.any? %>
    <% @recipes.errors.full_messages.each do |msg| %>
        <br><%= msg %>
    <% end %>
<% end %>

<%= form_for @recipes do |f| %>
  
  <%= f.label :tittle, 'Nome' %>
  <%= f.text_field :tittle %> 
  <%= f.label :recipe_type_id, 'Tipo de receita' %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name, {prompt: "Selecione..."}, {class: "select_recipe_type"} %>
  <%= f.label :cuisine, 'Cozinha' %>
  <%= f.text_field :cuisine %>
  <%= f.label :difficulty, 'Dificuldade' %>
  <%= f.text_field :difficulty %>
  <%= f.label :cook_time, 'Tempo de cozimento' %>
  <%= f.number_field :cook_time %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_area :ingredients %>
  <%= f.label :cook_method, 'Modo de Preparo' %>
  <%= f.text_area :cook_method %>

  <%= f.submit 'Enviar' %></p>
  <%= link_to 'Voltar', root_path, class: 'botao_voltar' %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>
<%= render partial: 'form_recipes' %>

app/views/recipes/index.html.erb

<% @recipes.each do |recipe| %>
  <%= link_to recipe do %>
    <div class="quadro">
      <h1 align="center"><%= recipe.tittle %></h1>
      <ul>
        <li>Tipo de Receita: <%= recipe.recipe_type.name %></li>
        <li>Cozinha: <%= recipe.cuisine %></li>
        <li>Dificuldade: <%= recipe.difficulty %></li>
        <li>Cozimento: <%= recipe.cook_time_min %></li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/recipes/my_recipes.html.erb
<% if @recipes.empty? %>
  <br><p>Nenhuma receita encontrada.</p>
<% else %>
<h1>Minhas Receitas</h1>
  <% @recipes.each do |recipe| %>  
    <h2><%= link_to recipe.tittle, recipe %></h2>
    <p>Receita enviada em <%= recipe.form_date(recipe.created_at) %></p><br>
  <% end %>
<% end %>
<%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipes/new.html.erb
<h1>Nova Receita</h1>    
<%= render partial: 'form_recipes' %>

app/views/recipes/search.html.erb
<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.tittle, recipe %></h1>
<% end %>
<%= link_to 'Voltar', root_path, class: 'botao_voltar' %>

app/views/recipes/show.html.erb

  <h1><%= @recipes.tittle %></h1>
  <ul>
    <li>Tipo de Receita: <%= @recipes.recipe_type.name %></li>
    <li>Tipo de Cozinha: <%= @recipes.cuisine %></li>
    <li>Dificuldade: <%= @recipes.difficulty %></li>
    <li>Tempo de Preparo: <%= @recipes.cook_time_min %></li>
  </ul>

  <h3>Ingredientes</h3>
  <p><%= @recipes.ingredients %></p>
  <h3>Modo de Preparo</h3>
  <p><%= @recipes.cook_method %></p>
  <br>
  <p>Receita enviada por <%= @recipes.user.email %>.</p>
  <br>

  <% if user_signed_in? && current_user.recipe_owner?(@recipes) %>
    <%= link_to 'Editar Receita', edit_recipe_path %>
  <% end %>

  <%= link_to 'Voltar', root_path, class: 'botao_voltar' %>